[package]
name = "protin"
version = "2.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.7.1"
actix-governor = "0.10.0"
actix-multipart = "0.8.0"
actix-web = "4.15.0"
anyhow = "1.0.104"
aws-config = { version = "1.11.0", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.143.0"
base64 = "0.23.1"
diesel = { version = "2.3.12", features = ["postgres", "r2d2"] }
diesel_migrations = { version = "2.3.2", features = ["postgres"] }
dotenvy = "0.15.7"
env_logger = "0.11.11"
log = "0.4.34"
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
