[package]
name = "protin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-multipart = "0.4.0"
actix-web = "4.2.1"
anyhow = "1.0.68"
diesel = { version = "2.0.0", features = ["postgres", "r2d2", "uuid"] }
dotenvy = "0.15.6"
env_logger = "0.10.0"
futures-util = { version = "0.3.25", default-features = false, features = ["std"] }
log = "0.4.17"
rand = "0.8.5"
rust-s3 = "0.32.3"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
uuid = { version = "1.2.2", features = ["v4", "serde"] }
