events { }
http {
    server {
        server_name protin.dfirebird.dev;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}