openapi: 3.0.3
info:
  title: Protin
  description: |-
    Protin is a text storage application, that can be used to store code and text data temporarily to share them across the internet. It is perfect tool to share code, logs, etc., on the internet chats such as IRC, Discord or Matrix.
  contact:
    email: me@dfirebird.dev
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
  - url: https://protin.dfirebird.dev/api/
tags:
  - name: paste
    description: Access and create pastes
paths:
  /paste:
    post:
      tags:
        - paste
      summary: Create a new paste
      description: Create a new paste
      requestBody:
        content:
          multipart/form-data: # Media type
            schema: # Request payload
              type: object
              properties: # Request parts
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: text/plain
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Paste"
        "404":
          description: Multipart form data sent is either incomplete or does not have the required field
  /paste/{pasteId}:
    get:
      tags:
        - paste
      summary: Retrieve paste by ID
      description: Returns the paste coressponding to provided ID
      parameters:
        - name: pasteId
          in: path
          description: ID of paste return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: A test paste
        "400":
          description: Invalid ID supplied
        "404":
          description: Paste not found
components:
  schemas:
    Paste:
      type: object
      properties:
        id:
          type: integer
          format: int64
        file_path:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time
