name: Container Image CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

env:
  UI_IMAGE_NAME: protin_ui
  API_IMAGE_NAME: protin_api

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repsitory
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Prepare version metadata
        id: meta
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Prepare image base name
        id: image_base
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER=$OWNER" >> $GITHUB_OUTPUT
          echo "Image owner: $OWNER"

      - name: Build and push UI image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: ./protin-frontend
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.image_base.outputs.OWNER }}/${{ env.UI_IMAGE_NAME }}:${{ steps.meta.outputs.VERSION }}
          labels: runnumber=${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push API image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: ./protin-backend
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.image_base.outputs.OWNER }}/${{ env.API_IMAGE_NAME }}:${{ steps.meta.outputs.VERSION }}
          labels: runnumber=${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
